version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Enable hot-reloading
      - ./src:/app/src
      - ./public:/app/public
    stdin_open: true
    tty: true
    command: npm start
    environment:
      - NODE_ENV=development
